# version: '3.5'

# services:
#   postgres:
#     container_name: postgres
#     image: postgres:9.6.23
#     environment:
#       POSTGRES_USER: ${POSTGRES_USER:-postgres}
#       POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
#       POSTGRES_DB: ${POSTGRES_DB:-keycloak}
#     ports:
#       - "${POSTGRES_PORT:-5432}:5432"
#     volumes:
#       - $HOME/docker/volumes/postgres:/var/www/html   # I will share my code so I map this path



version: '3.8'
services:
  db:
    image: postgres:14.1-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    ports:
      - '5432:5432'
    volumes: 
      - db:/var/lib/postgresql/data
volumes:
  db:
    driver: local