version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:9.6.23
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-keycloak}
    networks:
      - axebug-network
    ports:
      - "${POSTGRES_PORT:-5432}:5432"


  keycloak:
    container_name: keycloak
    image: epiphanyplatform/keycloak:14.0.0
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: postgres
      DB_DATABASE: ${POSTGRES_DB:-keycloak}
      DB_USER: ${POSTGRES_USER:-postgres}
      DB_SCHEMA: public
      DB_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      KEYCLOAK_USER: ${KEYCLOAK_USER:-admin}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD:-admin}
    networks:
      - axebug-network
    ports:
      - "${KEYCLOAK_PORT:-9090}:8082"
    depends_on:
      - postgres
    restart: always

  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3.9.11-management
    environment:
      RABBITMQ_DEFAULT_USER: admin
      RABBITMQ_DEFAULT_PASS: admin
    networks:
      - axebug-network
    ports:
      - "${RABBITMQ_PORT:-5672}:5672"
      - "${RABBITMQ_PANEL_PORT:-15034}:15672"
#    volumes:
#      - D:\volumes\pgadmin:/var/lib/pgadmin

  axebug-web:
    container_name: axebug-web
    image: ctekkaya/axebug-web:0.1.0
    networks:
      - axebug-network
    ports:
      - "3000:3000"

  axebug-server:
    container_name: axebug-server
    image: ctekkaya/axebug-server:0.1.0
    networks:
      - axebug-network
    ports:
      - "8080:8080"

networks:
  axebug-network:
    name: axebug-network