version: '3.5'

services:
  postgres:
    container_name: postgres
    image: postgres:9.6.23
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-postgres}
      POSTGRES_DB: ${POSTGRES_DB:-keycloak}
    networks:
      - elekon-network
    ports:
      - "${POSTGRES_PORT:-5432}:5432"
    
  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4:5
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    networks:
      - elekon-network
    #    volumes:
    #      - D:\volumes\pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-15033}:80"





networks:
  elekon-network:
    name: elekon-network