version: '3.4'

services:

  axebug-server:
    container_name: axebug-server
    image: ctekkaya/axebug-server:0.1.3
    networks:
      - axebug-network
    ports:
      - "8080:8080"

networks:
  axebug-network:
    name: axebug-network
